version: '3.8'

volumes:
  ngnix_data:
  ngnix_letsencrypt:
  mysql_db_storage:

services:
  ngnix:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"    # Public HTTP Port
      - "443:443"  # Public HTTPS Port
      - "81:81"    # Admin Web Port
    environment:
      # MySQL connection parameters
      DB_MYSQL_HOST=db
      DB_MYSQL_PORT=3306
      DB_MYSQL_USER=${MYSQL_USER}
      DB_MYSQL_PASSWORD=${MYSQL_PASSWORD}
      DB_MYSQL_NAME=${MYSQL_DATABASE}
      # Uncomment if IPv6 is not enabled
      # DISABLE_IPV6: 'true'
    volumes:
      - ngnix_data:/data
      - ngnix_letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      MARIADB_AUTO_UPGRADE='1'
    volumes:
      - mysql_db_storage:/var/lib/mysql
